config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'cn' => 'home#locale_redirect', locale: 'zh-CN'
  get 'en' => 'home#locale_redirect', locale: 'en'
  if false
    get 'instruction' => 'home#instruction'
    get 'refund' => 'home#refund'
  end

  # namecard scan portal
  get 'community_portal' => 'home#comm_portal'
  get 'social_portal' => 'home#comm_portal'

  devise_for :users
  resources :users

  resources :posts, only: [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  before_save :set_default_author

  scope :ordered, -> { order("publish_at desc") }
  scope :published, -> { where("publish_at is NOT NULL and publish_at < ?", Time.now) }

  has_attached_file :cover, :styles => {:thumb => "200x76#", :cover => "1000x382#"},
                            :url => "/ckeditor_assets/post/:id/:style/:filename",
                            :path => ":rails_root/public/ckeditor_assets/post/:id/:style/:filename"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  attr_accessor :delete_cover
  before_validation { self.cover = nil if self.delete_cover == '1' }


  protected
  def published?
    !!publish_at
  end

  def set_default_author
    self.author ||= user.try(:display_name)
  end

  rails_admin do
    weight 20
    list do
      filters [:title, :publish_at]
      field :id
      field :title
      field :subtitle
      field :author
      field :publish_at
      field :updated_at
    end

    edit do
      field :title do
        required true
      end
      field :subtitle
      field :author do
         help "显示的作者名，如果不填，使用当前发布用户的显示名"
      end
      field :cover do
        # for images. Will default to full size image, which might break the layout
        thumb_method :thumb
        # actually not needed in this case: default is "delete_#{field_name}" if the object responds to it
        delete_method :delete_cover
        help "建议 1000x382"
      end
      field :publish_at, :datetime do
        help "可设置预约发布时间；如果不填表示不发布"
        strftime_format "%Y-%m-%d %H:%M"
      end

      field :abstract, :ck_editor do
        required true
      end
      field :content, :ck_editor do
        required true
      end

    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.ordered.published.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.published.find(params[:id])
  end

  # # GET /posts/new
  # def new
  #   @post = Post.new
  # end
  #
  # # GET /posts/1/edit
  # def edit
  # end
  #
  # # POST /posts
  # # POST /posts.json
  # def create
  #   @post = Post.new(post_params)
  #
  #   respond_to do |format|
  #     if @post.save
  #       format.html { redirect_to @post, notice: 'Post was successfully created.' }
  #       format.json { render :show, status: :created, location: @post }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /posts/1
  # # PATCH/PUT /posts/1.json
  # def update
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /posts/1
  # # DELETE /posts/1.json
  # def destroy
  #   @post.destroy
  #   respond_to do |format|
  #     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post_card.html.erb
<div class="well post">
  <%= image_tag post.cover.url(:cover), class: 'img-responsive img-full', alt: post.title if post.cover.file? %>

  <div class="modal-header">
    <h4 class="modal-title">
      <h2><%= post.title %></h2>
      <% if post.subtitle %>
        <h3><%= post.subtitle %></h3>
      <% end %>
      <figure>
        <figcaption><a href="#"><%= post.author %></a> on <%= l post.publish_at.to_date %></figcaption>
      </figure>
    </h4>
  </div>
  <div class="modal-body">
    <%= post.abstract.try(:html_safe) %>

    <hr />

    <%= link_to t('site.posts.read_more'), post_path(post), class: 'btn btn-primary withripple' %>
  </div>
</div>

app/views/posts/_post_detail.html.erb
<div class="well post-container post">
  <%= image_tag post.cover.url(:cover), class: "img-responsive img-full", alt: post.title if post.cover.file? %>

  <div class="modal-header">
    <h4 class="modal-title">
      <h2><%= post.title %></h2>
      <% if post.subtitle %>
        <h3><%= post.subtitle %></h3>
      <% end %>
      <figure>
        <figcaption><a href="#"><%= post.author %></a> on <%= l post.publish_at.to_date %></figcaption>
      </figure>
    </h4>
  </div>
  <div class="modal-body">
    <%= post.content.try(:html_safe) %>

    <hr />

    <%= link_to t('site.posts.back'), posts_path, class: 'btn btn-primary withripple' %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @body_class = "landing-page normal" %>

<div class="container post-container">
  <div class="row">

    <%= render :partial => "post_card", collection: @posts, as: :post %>

  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% @body_class = "landing-page normal" %>

<div class="container">
  <div class="row">

    <%= render :partial => "post_detail", object: @post, as: :post %>

  </div>
</div>